### ISSUE TITLE
How to upload file again

### ISSUE THREAD

**Issue by zpf7879** [aws-samples/amazon-s3-multipart-upload-transfer-acceleration#15] opened 2023-12-15 01:41 UTC
It seems like after you select a file, the upload will be triggered. How can I upload a second, third, and more files? I tried to select a different file and it seems no reaction. It would be more intuitive to add a button "upload" to trigger the uploading action after a file is selected. Currently, I have to refresh the page, and refill the settings, and then choose a different file to upload.

**Comment by akomandooru** [comment] 2023-12-16 18:28
Selecting a second file after your first file is complete is similar to selecting the first file and it should upload automatically. Please check on two things - wait for sometime for the second file to processed and the progress should show; also, check if you see any errors in your console log. You can also debug the handler in your browser to check if the code is getting triggered when you select the second file. I tried this with the latest source just now and the second, third, files uploaded as expected. Adding an upload button is a good idea - I will consider this in my next project. Thank you.

I will wait for you response for a week before closing this issue.

**Comment by akomandooru** [comment] 2024-01-18 19:23
Closing this issue due to inactivity; please feel free to re-open with specifics about the browser and the steps you took to reproduce the issue.

**Closed by akomandooru** 2024-01-18 19:23 UTC
